### ISSUE TITLE
Tune Shooter, Pivot, Intake, & Transport speed

### ISSUE THREAD

**Issue by vijayn7** [hackbots-3414/2024_CRESCENDO#117]
- [ ] Remake Lookup table
- [ ] Speed Up pivot speed
- [ ] test for optimal Intake & transport speed combo. (typically want intake as fast as possible)

**Comment by AkshayKumar41** [comment]
Lookup table: 
1) redo the min and max of pivot
2) add key-value pairs to Constants.ShooterConstants - Will auto interpolate and spit out correct numbers. Leave the speed at max as that was what we found to be best. 
3) test and make sure it works for all angles - if it doesn't work, add a key value pair at that point so it does

Pivot Speed: Scale Velocity with new Max - simple fix but didn't have time to test at comp. Along with this, we also want to remove the extra stow after shots for autons, as that was added to compensate - this should bring us back to being able to shoot the fifth piece. Finally, we also have to retune the time to shoot (SubsystemManager.makeShootAfterRev - or something like that. it has a .withTimeout(*time*) that has to be fixed)

Intake/Transport: hold off till we get a final decision from mech and cad about what were doing - might not even need to touch code for this
