### ISSUE TITLE
Auto Wheel Diameter

### ISSUE THREAD

**Issue by vijayn7** [hackbots-3414/2024_CRESCENDO#123]
See Here: https://github.com/Mechanical-Advantage/RobotCode2024/blob/main/src/main/java/org/littletonrobotics/frc2024/commands/WheelRadiusCharacterization.java

- [x] Compute DriveBase Radius
- [x] Access Gyro Rotations
- [x] Get Wheel Rotation Average
- [x] Spin Robot
- [x] Solve For Radius 
- [ ] Test on Robot

**Comment by AkshayKumar41** [comment]
Mech Advantage has a math equation that calculates wheel diameter given driveBaseRadius, gyro rads, and individual wheel rotations in rads. We have to make this a command on SmartDashboard - it will on initialize store off all your initial readings, on execute spin the robot some number of times (doesnt matter, but more = better value), and on end do the math to calculate diameter and send it to SmartDashboard. As for what you need for the equation:

1) driveBaseRadius is calculated by PathPlanner initialize in SubsystemManager - add it to smart dashboard once, as its a constant - it does the math for you. 
`double driveBaseRadius = 0;`
`for (var moduleLocation : drivetrain.moduleLocations()) {`
	`     driveBaseRadius = Math.max(driveBaseRadius, moduleLocation.getNorm());`
`}`
`SmartDashboard.putNumber("driveabase radius", driveBaseRadius);`

2) Gyro Rotations - log gyro rotations - what you can do is make a getGyroRad() method and run that on init and end. 
`SmartDashboard.putNumber("GYRO_RADS", Units.degreesToRadians(m_pigeon2.getAngle()));`

3) ^ same thing but do a getWheelRotationRadAvg() method - where you get all 4 wheel rotations average them, convert them to radians, and send that back
`for (int i = 0; i < Modules.length; i++) {`
`      SmartDashboard.putNumber("SWERVE MODULE MOVEMENT RADS" + i, `
`            (Modules[i].getDriveMotor().getPosition().getValueAsDouble() / 6.122448979591837) * Math.PI * 2.0);`
`}`

4) do the equation: `(gyroRads * driveRadius) / averageWheelRotationRads`

**Comment by vijayn7** [comment]
is coded on the branch but still needs to be tested on the robot
