### ISSUE TITLE
Auton Organization

### ISSUE THREAD

**Issue by vijayn7** [hackbots-3414/2024_CRESCENDO#126]
- [ ] Add choosers to elastic dashboard
- [ ] Filter off number of pieces
- [ ] starting position (Amp-side, middle, Source-side, other)

**Comment by AkshayKumar41** [comment]
Enums :) - DEBUG, ALLCOMP, SOURCE, AMP, CENTER
DEBUG: everything basically
ALLCOMP: everything tested
SOURCE: source side autons
AMP: amp side autons
CENTER: center autons

**Comment by vijayn7** [comment]
> Enums :) - DEBUG, ALLCOMP, SOURCE, AMP, CENTER DEBUG: everything basically ALLCOMP: everything tested SOURCE: source side autons AMP: amp side autons CENTER: center autons

Make these a constant in code and we filter from there perhaps
