### ISSUE TITLE
Fix Manual Elevator Move

### ISSUE THREAD

**Issue by vijayn7** [hackbots-3414/2024_CRESCENDO#128]
"Basically, when it goes all the way down, if bottom sensor triggered, entire system makes a loud noise and jerks up before settling down" - Akshay

I'm not sure exactly what this means so maybe talk to Akshay about this one

**Comment by therekrab** [comment]
when we manually moved the elevator down it was OK until the elevator hit the magnet and then we dhot the elevator up real fast back up a couple inches instead of keeping it at the bottom. It made a noise and shook the robot.
