### ISSUE TITLE
Configure drivetrain for selective AprilTag updates to odometry

### ISSUE THREAD

**Issue by bczdog** [hackbots-3414/2024_CRESCENDO#87]
Configure drivetrain such that AprilTags can be turned off, turned on, and turned on just for shooting.

AprilTag updates to odometry field-wide are coming online late in testing, limiting the opportunity to identify problems.  Configuring the drivetrain such that AprilTag enable / disable / shoot-only is visible on the dashboard and can be set by commands on the dashboard may be an important tool to mitigate risk.

One state is the quiet, on-the-fly update from anywhere AprilTags are visible.  This is the desired target state.

Second is a total disable of AprilTag processing.

Third is normally disabled processing, with the shoot commands enabling AprilTag  updates from just the Red or Blue alliance tag immediately under the speaker.  As there are two tags there, processing is further restricted to read only one of them to permit accurate ranging.  Once shooting completes, AprilTag updates turn completely off.

Commands on the dashboard can be used to toggle between states should Drive Team need to make adjustments on-the-fly.

**Comment by AkshayKumar41** [comment]
The best way to do this would be to route all PhotonVision through subsystem manager instead of linking it with drivetrain. SubsystemManager has a periodic we can use. We would need to add a "isRunning" with getter and setter methods for shooter, and on periodic, an if statement on isRunning should make it easy to turn off and on.

**Comment by vijayn7** [comment]
Framework made and pulled to main in pull request #92. Still needs testing and further implementation.
